name: mello-api
services:
  mello-api:
    container_name: mello-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - ${API_PORT}:${API_PORT}
    restart: always
    networks:
      - mello-network
    command: npm run dev
    depends_on:
      - mello-db
    env_file:
      - .env

  mello-db:
    container_name: mello-db
    image: mongo #Retire a versão para maquinas com processador atual || mongo:4.2 ou mongo
    restart: always
    networks:
      - mello-network
    env_file:
      - .env
    ports:
      - "27017:27017" 
    volumes:
      - mello-db-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo_express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    networks:
      - mello-network
    depends_on:
      - mello-db
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:admin123@mello-db:27017/mello-db?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mello-db-data:

networks:
  mello-network:
    driver: bridge